/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReadIdentifierRouteImport } from './routes/read/$identifier'
import { Route as ReadManifestManifestRouteImport } from './routes/read/manifest/$manifest'
import { Route as ReadExperimentalIdentifierRouteImport } from './routes/read/experimental/$identifier'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReadIdentifierRoute = ReadIdentifierRouteImport.update({
  id: '/read/$identifier',
  path: '/read/$identifier',
  getParentRoute: () => rootRouteImport,
} as any)
const ReadManifestManifestRoute = ReadManifestManifestRouteImport.update({
  id: '/read/manifest/$manifest',
  path: '/read/manifest/$manifest',
  getParentRoute: () => rootRouteImport,
} as any)
const ReadExperimentalIdentifierRoute =
  ReadExperimentalIdentifierRouteImport.update({
    id: '/read/experimental/$identifier',
    path: '/read/experimental/$identifier',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/read/$identifier': typeof ReadIdentifierRoute
  '/read/experimental/$identifier': typeof ReadExperimentalIdentifierRoute
  '/read/manifest/$manifest': typeof ReadManifestManifestRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/read/$identifier': typeof ReadIdentifierRoute
  '/read/experimental/$identifier': typeof ReadExperimentalIdentifierRoute
  '/read/manifest/$manifest': typeof ReadManifestManifestRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/read/$identifier': typeof ReadIdentifierRoute
  '/read/experimental/$identifier': typeof ReadExperimentalIdentifierRoute
  '/read/manifest/$manifest': typeof ReadManifestManifestRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/read/$identifier'
    | '/read/experimental/$identifier'
    | '/read/manifest/$manifest'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/read/$identifier'
    | '/read/experimental/$identifier'
    | '/read/manifest/$manifest'
  id:
    | '__root__'
    | '/'
    | '/read/$identifier'
    | '/read/experimental/$identifier'
    | '/read/manifest/$manifest'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ReadIdentifierRoute: typeof ReadIdentifierRoute
  ReadExperimentalIdentifierRoute: typeof ReadExperimentalIdentifierRoute
  ReadManifestManifestRoute: typeof ReadManifestManifestRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/read/$identifier': {
      id: '/read/$identifier'
      path: '/read/$identifier'
      fullPath: '/read/$identifier'
      preLoaderRoute: typeof ReadIdentifierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/read/manifest/$manifest': {
      id: '/read/manifest/$manifest'
      path: '/read/manifest/$manifest'
      fullPath: '/read/manifest/$manifest'
      preLoaderRoute: typeof ReadManifestManifestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/read/experimental/$identifier': {
      id: '/read/experimental/$identifier'
      path: '/read/experimental/$identifier'
      fullPath: '/read/experimental/$identifier'
      preLoaderRoute: typeof ReadExperimentalIdentifierRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ReadIdentifierRoute: ReadIdentifierRoute,
  ReadExperimentalIdentifierRoute: ReadExperimentalIdentifierRoute,
  ReadManifestManifestRoute: ReadManifestManifestRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
